[package]
name = "hookbuffer"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.28"
reqwest = { version = "0.11.18", features = ["json"] }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.96"
tokio = { version = "1.28.2", features = ["full"] }
twilight-model = "0.15.2"
warp = "0.3.5"
