[package]
name = "hookbuffer"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
futures = "0.3.31"
reqwest = { version = "0.12.12", features = ["json"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
serial_test = "3.2.0"
tokio = { version = "1.43.0", features = ["full"] }
twilight-model = "0.16.0"
warp = "0.3.7"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
