[package]
name = "hookbuffer"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.21.4"
futures = "0.3.28"
reqwest = { version = "0.11.18", features = ["json"] }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.96"
serial_test = "2.0.0"
tokio = { version = "1.28.2", features = ["full"] }
twilight-model = "0.15.2"
warp = "0.3.5"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
