[workspace]
members = [
"cf-worker",
# "standalone",
# "shared-lib"
]
resolver = "2"

[workspace.dependencies]
# shared-lib = { path = "./shared-lib" }
serde_json = "1.0.139"
serde = { version = "1.0.217", features = ["derive"] }
reqwest = { version = "0.12.12", features = ["json"] }
