# fly.toml app configuration file generated for hookbuffer on 2023-10-14T01:01:00-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hookbuffer"
primary_region = "ord"

[build]
  image = "ghcr.io/cbackas/hookbuffer:latest"
  build-target = "runtime"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
