# See https://fly.io/docs/reference/configuration/

app = "hookbuffer"
primary_region = "ord"

[build]
  # image = "ghcr.io/cbackas/hookbuffer:latest"
  build-target = "runtime"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  RUST_LOG = "hookbuffer-standalone=debug"

[checks]
  [checks.health]
    grace_period = "60s"
    interval = "30s"
    method = "get"
    path = "/healthcheck"
    port = 8000
    timeout = "10s"
    type = "http"
