name = "hookbuffer"
main = "build/worker/shim.mjs"
compatibility_date = "2025-02-25"

[observability]
enabled = true

[build]
command = "cargo install -q worker-build && worker-build --release"

[durable_objects]
bindings = [
  { name = "HOOKBUFFER", class_name = "Queue" } # the `class_name` uses the Rust struct identifier name
]

[[migrations]]
tag = "v1"
new_classes = ["Queue"]
