[package]
name = "hookbuffer-standalone"
version = "3.2.0"
edition = "2021"

[dependencies]
shared-lib = {workspace = true, features=["standalone"]}
serde = {workspace = true}
serde_json = {workspace = true}
tracing = {workspace = true}
tokio = {workspace = true}
futures = "0.3.34"
serial_test = "4.0.1"
axum = { workspace = true}
tower-http = { version = "0.7.1", features = ["trace", "fs", "compression-gzip"] }
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
