name: Pull Request
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize
jobs:
  pr-title:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - name: Run clippy
        uses: giraffate/clippy-action@v1
        with:
          reporter: github-pr-check
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clippy_flags: --all-targets --all-features
      - name: Run rustfmt
        run: cargo fmt --all -- --check
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Run Tests
        run: |
          cargo test --verbose
  build:
    uses: ./.github/workflows/build.yml
